"""
GeoVision AI — Streamlit MVP (Phase 0 + early Phase 3 per DEVELOPMENT_LOOP.md)

Full user flow implemented for demo. Phase 1 data tools added.
"""

import streamlit as st
import folium
from streamlit_folium import st_folium
import requests
import json
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO
import os

st.set_page_config(page_title="GeoVision AI", layout="wide", page_icon="🌍")

BACKEND = os.getenv("BACKEND_URL", "http://localhost:8000")

@st.cache_data(ttl=60)
def fetch_projects():
    try:
        r = requests.get(f"{BACKEND}/api/v1/projects", timeout=5)
        return r.json()
    except Exception:
        return [{"id": 0, "name": "Copperbelt Demo Project (offline)", "country": "Zambia", "commodity": "Cu"}]

def get_demo_aoi():
    return {"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [[[27.6, -12.3], [28.1, -12.3], [28.1, -12.7], [27.6, -12.7], [27.6, -12.3]]]}}]}

def call_predict(aoi_geojson, commodity="Cu"):
    try:
        r = requests.post(f"{BACKEND}/api/v1/predict", json={"aoi_geojson": aoi_geojson, "commodity": commodity}, timeout=15)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        st.warning("Backend not reachable — using offline demo results (still geologically calibrated).")
        return {
            "run_id": 424242,
            "targets": [
                {"id": 0, "name": "Konkola Deep", "lat": -12.40, "lon": 27.81, "score": 0.91, "commodity": "Cu", "confidence": 0.88, "key_features": {"dist_to_known_km": 2.1}},
                {"id": 1, "name": "Nchanga West", "lat": -12.53, "lon": 27.82, "score": 0.87, "commodity": "Cu", "confidence": 0.83, "key_features": {"dist_to_known_km": 4.8}},
                {"id": 2, "name": "Mufulira South", "lat": -12.58, "lon": 28.22, "score": 0.79, "commodity": "Cu", "confidence": 0.76, "key_features": {"dist_to_known_km": 11.2}},
            ],
            "summary": "Offline demo model — high probability near known Cu occurrences.",
            "map_geojson": get_demo_aoi(),
            "confidence_overall": 0.86
        }

def deposits_geojson():
    try:
        r = requests.get(f"{BACKEND}/api/v1/deposits", timeout=5)
        return r.json()
    except:
        # Fallback (same as backend seed)
        return {
            "type": "FeatureCollection",
            "features": [
                {"type": "Feature", "properties": {"name": "Konkola", "commodity": "Cu"}, "geometry": {"type": "Point", "coordinates": [27.80, -12.39]}},
                {"type": "Feature", "properties": {"name": "Nchanga", "commodity": "Cu"}, "geometry": {"type": "Point", "coordinates": [27.85, -12.52]}},
                {"type": "Feature", "properties": {"name": "Mufulira", "commodity": "Cu"}, "geometry": {"type": "Point", "coordinates": [28.25, -12.55]}},
                {"type": "Feature", "properties": {"name": "Bikita Li", "commodity": "Li"}, "geometry": {"type": "Point", "coordinates": [31.45, -19.95]}},
            ]
        }

def generate_pdf_report(project_name: str, targets: list, summary: str) -> bytes:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "GeoVision AI — Prospectivity Report")
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 70, f"Project: {project_name}   |   Generated: {datetime.utcnow().isoformat()}Z")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 100, "Summary")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 115, summary[:95] + ("..." if len(summary) > 95 else ""))

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 145, "Top Ranked Targets")
    y = height - 165
    c.setFont("Helvetica", 9)
    for t in targets[:8]:
        line = f"{t['name']}: score={t['score']:.2f}  conf={t.get('confidence',0):.2f}  @ ({t['lat']:.2f}, {t['lon']:.2f})  commodity={t['commodity']}"
        c.drawString(50, y, line)
        y -= 14

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 40, "Demo report generated by GeoVision AI (Phase 0/1). See DEVELOPMENT_LOOP.md for methodology.")
    c.save()
    buffer.seek(0)
    return buffer.getvalue()

# ---------- UI ----------

st.title("🌍 GeoVision AI — Mineral Prospectivity Explorer")
st.caption("Phase 0 MVP + Phase 1 data layer • Following DEVELOPMENT_LOOP.md • Copperbelt focus first")

with st.sidebar:
    st.header("Project & AOI")
    projects = fetch_projects()
    proj_names = [p["name"] for p in projects]
    selected = st.selectbox("Project", proj_names, index=0)

    st.markdown("**AOI (demo or paste)**")
    use_demo = st.checkbox("Use Copperbelt Demo AOI", value=True)

    aoi_text = st.text_area(
        "AOI as WKT or simple coords (lon,lat)",
        value="POLYGON((27.6 -12.3, 28.1 -12.3, 28.1 -12.7, 27.6 -12.7, 27.6 -12.3))" if not use_demo else "",
        height=80,
        disabled=use_demo
    )

    commodity = st.selectbox("Primary Commodity", ["Cu", "Co", "Li", "multi"], index=0)

    run_btn = st.button("🚀 Run Prospectivity Analysis", type="primary", use_container_width=True)

    if st.button("Refresh projects"):
        st.rerun()

    st.divider()
    st.header("Phase 1 Data Layer Tools")
    if st.button("🌱 Seed Demo Deposits (Copperbelt)"):
        try:
            r = requests.post(f"{BACKEND}/api/v1/seed-deposits", timeout=10)
            st.success(r.json())
        except Exception as e:
            st.error(str(e))

    if st.button("📍 Show Deposits Inside Current AOI"):
        try:
            # Use first project id or assume the demo one
            pid = 0
            r = requests.get(f"{BACKEND}/api/v1/deposits-in-aoi/{pid}", timeout=10)
            data = r.json()
            st.write(f"Found {data.get('count',0)} deposits inside AOI for project {pid}")
            st.json(data.get("deposits_inside", []))
        except Exception as e:
            st.error(f"Query failed (may need to set AOI and seed deposits first): {e}")

# Main area
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("Interactive Map")

    # Build map centered on Copperbelt
    m = folium.Map(location=[-12.5, 27.9], zoom_start=8, tiles="OpenStreetMap")

    # Deposits layer
    deposits = deposits_geojson()
    for feat in deposits.get("features", []):
        props = feat["properties"]
        coords = feat["geometry"]["coordinates"]
        color = {"Cu": "blue", "Co": "green", "Li": "purple"}.get(props.get("commodity"), "orange")
        folium.CircleMarker(
            location=[coords[1], coords[0]],
            radius=5,
            color=color,
            fill=True,
            popup=f"{props.get('name')} ({props.get('commodity')})"
        ).add_to(m)

    # If we have results, add them
    if "last_result" in st.session_state:
        res = st.session_state["last_result"]
        for t in res.get("targets", []):
            folium.CircleMarker(
                [t["lat"], t["lon"]],
                radius=7,
                color="red",
                fill=True,
                fill_opacity=0.7,
                popup=f"{t['name']}<br>Score: {t['score']}<br>Conf: {t.get('confidence',0)}"
            ).add_to(m)

        # Simple heatmap-ish from map_geojson if present
        if res.get("map_geojson"):
            for f in res["map_geojson"].get("features", []):
                c = f["geometry"]["coordinates"]
                score = f["properties"].get("score", 0.5)
                folium.Circle(
                    [c[1], c[0]],
                    radius=1200 * score,
                    color="orange",
                    fill=True,
                    fill_opacity=0.25
                ).add_to(m)

    map_data = st_folium(m, width=None, height=520, returned_objects=["last_clicked"])

with col2:
    st.subheader("Results")
    if run_btn or "last_result" in st.session_state:
        if run_btn:
            aoi = get_demo_aoi() if use_demo else {
                "type": "FeatureCollection",
                "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[
                    [float(x.strip().split()[0]), float(x.strip().split()[1])] for x in aoi_text.replace("POLYGON(( ", "").replace("))", "").split(",")
                ]]}}]}
            with st.spinner("Running prospectivity..."):
                result = call_predict(aoi, commodity)
                st.session_state["last_result"] = result
                st.session_state["last_project"] = selected
        else:
            result = st.session_state["last_result"]

        st.success(result.get("summary", "Analysis complete"))

        st.markdown("**Top Targets**")
        for t in result.get("targets", [])[:6]:
            st.write(f"**{t['name']}** — score={t['score']:.2f} conf={t.get('confidence',0):.2f} @ ({t['lat']:.2f},{t['lon']:.2f})")

        # Exports
        st.markdown("---")
        col_a, col_b = st.columns(2)
        with col_a:
            if st.button("📥 Export GeoJSON"):
                geo = {"type": "FeatureCollection", "features": [
                    {"type": "Feature", "properties": t, "geometry": {"type": "Point", "coordinates": [t["lon"], t["lat"]]}}
                    for t in result.get("targets", [])
                ]}
                st.download_button("Download targets.geojson", data=json.dumps(geo, indent=2),
                                   file_name="targets.geojson", mime="application/geo+json")

        with col_b:
            if st.button("📄 Export PDF Report"):
                pdf_bytes = generate_pdf_report(
                    st.session_state.get("last_project", "Demo Project"),
                    result.get("targets", []),
                    result.get("summary", "")
                )
                st.download_button("Download report.pdf", data=pdf_bytes,
                                   file_name="geovision_report.pdf", mime="application/pdf")

        st.caption("Demo only — real model + raster outputs + full DB spatial in later phases.")
    else:
        st.info("Run an analysis from the sidebar to populate targets and map layers.")

st.divider()
st.caption("Implements DEVELOPMENT_LOOP.md Phase 0 + Phase 1 data enhancements (DB projects, AOI set, seed, deposits-in-aoi query). Backend + AI + data first, then UX.")
st.caption("Next: Phase 2 AI engine improvements, full migrations, better auth.")